In [2]:
import pandas as pd
import numpy as np
import os
from datetime import datetime

In [14]:
def getdata(company,sources):
    stock = pd.read_csv("StockData/" + company + "_pred"+ '.csv')
    dates = stock.iloc[:,0].values
    #labels = stock.iloc[:,8].values
    diff = stock.iloc[:,7].values
    dates_label = {}
    for i, date in enumerate(dates):
        if '/' in date:
            replace = datetime.strptime(date,"%m/%d/%y")
            date = datetime.strftime(replace, "%Y-%m-%d")
        dates_label[date] = diff[i]
    news = pd.read_csv("Prediction/" + company + "_" + sources + "_prediction.csv",encoding='latin-1')
    result = {} # date, content_score
    result_file = "result/" + company + "_" + sources + "_prediction.csv"
    for _, row in news.iterrows():
        if '/' in row['dates']:
            replace = datetime.strptime(row['dates'],"%m/%d/%y")
            dd = datetime.strftime(replace, "%Y-%m-%d")
        else:
            dd = row['dates']
        result[dd] = result.get(dd,[]) + [row['content_scores']]
    final = {}
    d = list(result.keys())
    d.sort()
    for key in d:
        if key in dates_label:
            result[key] = np.mean(result[key])
            final['Dates'] = final.get('Dates', []) + [key]
            final['content_scores'] = final.get('content_scores',[]) + [result[key]]


    result = {}
    for _, row in news.iterrows():
        if '/' in row['dates']:
            replace = datetime.strptime(row['dates'],"%m/%d/%y")
            dd = datetime.strftime(replace, "%Y-%m-%d")
        else:
            dd = row['dates']
        result[dd] = result.get(dd,[]) + [row['title_score']]
    for key in final['Dates']:
        final['title_scores'] = final.get('title_scores',[]) + [np.mean(result[key])]
    result = {}
    for _, row in news.iterrows():
        if '/' in row['dates']:
            replace = datetime.strptime(row['dates'],"%m/%d/%y")
            dd = datetime.strftime(replace, "%Y-%m-%d")
        else:
            dd = row['dates']
        result[dd] = result.get(dd,[]) + [row['firstP_score']]
    for key in final['Dates']:
        final['firstP_scores'] = final.get('firstP_scores',[]) + [np.mean(result[key])]
        #final['stock_label'] = final.get('stock_label',[]) + [dates_label[key][0]]
        final['diff'] = final.get('diff',[]) + [dates_label[key]]

    data = pd.DataFrame.from_dict(final)
    data.to_csv(result_file)

In [15]:
companies = ["NFLX", "FB","BA", "TSLA"]
sources = ["yahoo.com","businessinsider.com","marketwatch.com"]
for c in companies:
#c = 'NFLX'
    for s in sources:
#s = 'yahoo.com'
        getdata(c,s)
#print(data)

{'2019-04-11': 2.649994, '2019-04-12': -9.549987, '2019-04-15': -1.839996, '2019-04-16': 4.4599910000000005, '2019-04-17': -10.309998, '2019-04-18': 5.350006}
{'2019-04-11': 2.649994, '2019-04-12': -9.549987, '2019-04-15': -1.839996, '2019-04-16': 4.4599910000000005, '2019-04-17': -10.309998, '2019-04-18': 5.350006}
{'2019-04-11': 2.649994, '2019-04-12': -9.549987, '2019-04-15': -1.839996, '2019-04-16': 4.4599910000000005, '2019-04-17': -10.309998, '2019-04-18': 5.350006}
{'2019-04-11': -0.73001, '2019-04-12': 1.100006, '2019-04-15': 1.149994, '2019-04-16': -0.13000499999999998, '2019-04-17': -0.8200069999999999, '2019-04-18': -0.520004}
{'2019-04-11': -0.73001, '2019-04-12': 1.100006, '2019-04-15': 1.149994, '2019-04-16': -0.13000499999999998, '2019-04-17': -0.8200069999999999, '2019-04-18': -0.520004}
{'2019-04-11': -0.73001, '2019-04-12': 1.100006, '2019-04-15': 1.149994, '2019-04-16': -0.13000499999999998, '2019-04-17': -0.8200069999999999, '2019-04-18': -0.520004}
{'2019-04-11': 5.5400089999999995, '2019-04-12': 3.890015, '2019-04-15': -1.2400209999999998, '2019-04-16': 5.2099910000000005, '2019-04-17': -6.580017, '2019-04-18': 2.550018}
{'2019-04-11': 5.5400089999999995, '2019-04-12': 3.890015, '2019-04-15': -1.2400209999999998, '2019-04-16': 5.2099910000000005, '2019-04-17': -6.580017, '2019-04-18': 2.550018}
{'2019-04-11': 5.5400089999999995, '2019-04-12': 3.890015, '2019-04-15': -1.2400209999999998, '2019-04-16': 5.2099910000000005, '2019-04-17': -6.580017, '2019-04-18': 2.550018}
{'2019-04-11': 0.120025, '2019-04-12': -2.519989, '2019-04-15': -2.25, '2019-04-16': 7.609985000000001, '2019-04-17': -3.519989, '2019-04-18': 2.029999}
{'2019-04-11': 0.120025, '2019-04-12': -2.519989, '2019-04-15': -2.25, '2019-04-16': 7.609985000000001, '2019-04-17': -3.519989, '2019-04-18': 2.029999}
{'2019-04-11': 0.120025, '2019-04-12': -2.519989, '2019-04-15': -2.25, '2019-04-16': 7.609985000000001, '2019-04-17': -3.519989, '2019-04-18': 2.029999}

In [10]:
data

        Dates  content_scores  title_scores  firstP_scores       diff
0  2019-04-11        0.408663      0.735100       0.249450   2.649994
1  2019-04-12        0.301296      0.125075       0.224117  -9.549987
2  2019-04-15        0.221650      0.000000       0.118850  -1.839996
3  2019-04-16        0.174302      0.052343       0.285604   4.459991
4  2019-04-17        0.209415      0.140957       0.142855 -10.309998